# Generated by Django 5.0.4 on 2024-06-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_alter_sell_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='baths',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='rooms',
            field=models.CharField(max_length=5),
        ),
    ]
